# AvaKill Default Policy
# Balanced security with common-sense defaults

version: "1.0"
default_action: deny

policies:
  # --- Allow read-only operations ---
  - name: allow-read-operations
    tools:
      - "*_read"
      - "*_get"
      - "*_list"
      - "*_search"
      - "*_query"
    action: allow
    message: "Read operations are allowed by default"

  # --- Block destructive SQL ---
  - name: block-destructive-sql
    tools:
      - "database_*"
      - "sql_*"
    action: deny
    conditions:
      args_match:
        query: ["DROP", "DELETE", "TRUNCATE", "ALTER"]
    message: "Destructive SQL operations require manual execution"

  # --- Block dangerous shell commands ---
  - name: block-dangerous-shell
    tools:
      - "shell_*"
      - "bash_*"
      - "command_*"
    action: deny
    conditions:
      args_match:
        cmd: ["rm -rf", "sudo", "chmod 777", "mkfs", "> /dev/"]
    message: "Dangerous shell commands are blocked"

  # --- Rate limit search and execution ---
  - name: rate-limit-search
    tools:
      - "web_search"
      - "code_execute"
    action: allow
    rate_limit:
      max_calls: 30
      window: "1m"
    message: "Rate limited to 30 calls per minute"

  # --- Require approval for sensitive operations ---
  - name: require-approval-sensitive
    tools:
      - "email_send"
      - "file_delete"
      - "api_delete"
    action: require_approval
    message: "This operation requires human approval"
