# AvaKill Default Policy
# Balanced security with common-sense defaults.
# Works out-of-the-box with the quickstart examples.

version: "1.0"
default_action: deny

policies:
  # --- Block destructive operations (must come before allows) ---
  - name: block-destructive-ops
    tools:
      - "delete_*"
      - "remove_*"
      - "destroy_*"
      - "drop_*"
      - "*_delete"
      - "*_remove"
      - "*_destroy"
      - "*_drop"
    action: deny
    message: "Destructive operations are blocked. Run manually or update your policy."

  # --- Block destructive SQL ---
  - name: block-destructive-sql
    tools:
      - "database_*"
      - "sql_*"
      - "execute_sql"
      - "run_query"
    action: deny
    conditions:
      args_match:
        query: ["DROP", "DELETE", "TRUNCATE", "ALTER"]
    message: "Destructive SQL blocked. Use a manual migration."

  # --- Block dangerous shell commands ---
  - name: block-dangerous-shell
    tools:
      - "shell_*"
      - "bash_*"
      - "command_*"
      - "run_command"
    action: deny
    conditions:
      args_match:
        command: ["rm -rf", "sudo", "chmod 777", "mkfs", "> /dev/"]
    message: "Dangerous shell command blocked."

  # --- Rate limit web search (must come before allow-read-operations) ---
  - name: rate-limit-web-search
    tools:
      - "web_search"
    action: allow
    rate_limit:
      max_calls: 30
      window: "1m"

  # --- Allow read-only operations (prefix and suffix patterns) ---
  - name: allow-read-operations
    tools:
      - "search_*"
      - "get_*"
      - "list_*"
      - "read_*"
      - "query_*"
      - "fetch_*"
      - "find_*"
      - "lookup_*"
      - "*_search"
      - "*_get"
      - "*_list"
      - "*_read"
      - "*_query"
      - "*_fetch"
      - "*_find"
      - "*_lookup"
    action: allow

  # --- Allow safe SQL (after destructive SQL is blocked above) ---
  - name: allow-safe-sql
    tools:
      - "database_*"
      - "sql_*"
      - "execute_sql"
      - "run_query"
    action: allow

  # --- Allow safe shell (after dangerous commands are blocked above) ---
  - name: allow-safe-shell
    tools:
      - "shell_*"
      - "bash_*"
      - "command_*"
      - "run_command"
    action: allow
