# AvaKill Default Policy
# Balanced security with common-sense defaults.
# Works out-of-the-box with the quickstart examples.
#
# Includes native tool names from popular AI coding agents:
#   Claude Code, Gemini CLI, Cursor, Windsurf, OpenAI Codex

version: "1.0"
default_action: deny

policies:
  # --- Block destructive operations (must come before allows) ---
  - name: block-destructive-ops
    tools:
      - "delete_*"
      - "remove_*"
      - "destroy_*"
      - "drop_*"
      - "*_delete"
      - "*_remove"
      - "*_destroy"
      - "*_drop"
    action: deny
    message: "Destructive operations are blocked. Run manually or update your policy."

  # --- Block destructive SQL ---
  - name: block-destructive-sql
    tools:
      - "database_*"
      - "sql_*"
      - "execute_sql"
      - "run_query"
    action: deny
    conditions:
      args_match:
        query: ["DROP", "DELETE", "TRUNCATE", "ALTER"]
    message: "Destructive SQL blocked. Use a manual migration."

  # --- Block dangerous shell commands ---
  - name: block-dangerous-shell
    tools:
      # Canonical
      - "shell_execute"
      # Claude Code
      - "Bash"
      # Gemini CLI
      - "run_shell_command"
      # Windsurf
      - "run_command"
      # OpenAI Codex
      - "shell"
      - "local_shell"
      - "exec_command"
      # Generic globs
      - "shell_*"
      - "bash_*"
      - "command_*"
    action: deny
    conditions:
      args_match:
        command: ["rm -rf", "sudo", "chmod 777", "mkfs", "> /dev/"]
    message: "Dangerous shell command blocked."

  # --- Rate limit web search (must come before allow-read-operations) ---
  - name: rate-limit-web-search
    tools:
      - "web_search"
      # Claude Code
      - "WebSearch"
    action: allow
    rate_limit:
      max_calls: 30
      window: "1m"

  # --- Allow read-only operations (prefix and suffix patterns) ---
  - name: allow-read-operations
    tools:
      # Claude Code
      - "Read"
      - "Glob"
      - "Grep"
      - "LS"
      - "WebFetch"
      # OpenAI Codex
      - "grep_files"
      # Generic globs (match canonical names and others)
      - "search_*"
      - "get_*"
      - "list_*"
      - "read_*"
      - "query_*"
      - "fetch_*"
      - "find_*"
      - "lookup_*"
      - "*_search"
      - "*_get"
      - "*_list"
      - "*_read"
      - "*_query"
      - "*_fetch"
      - "*_find"
      - "*_lookup"
    action: allow

  # --- Allow safe SQL (after destructive SQL is blocked above) ---
  - name: allow-safe-sql
    tools:
      - "database_*"
      - "sql_*"
      - "execute_sql"
      - "run_query"
    action: allow

  # --- Allow safe shell (shell_safe + command_allowlist) ---
  - name: allow-safe-shell
    tools:
      # Canonical
      - "shell_execute"
      # Claude Code
      - "Bash"
      # Gemini CLI
      - "run_shell_command"
      # Windsurf
      - "run_command"
      # OpenAI Codex
      - "shell"
      - "local_shell"
      - "exec_command"
      # Generic globs
      - "shell_*"
      - "bash_*"
      - "command_*"
    action: allow
    conditions:
      shell_safe: true
      command_allowlist:
        - echo
        - ls
        - cat
        - pwd
        - git
        - python
        - pip
        - npm
        - node
        - make
        - which
        - whoami
        - date
        - uname
        - head
        - tail
        - wc
        - file
        - stat
    message: "Safe shell commands allowed (no metacharacters)"
